// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductOrderBy int32

const (
	ProductOrderBy_BEST_SELLER ProductOrderBy = 0
	ProductOrderBy_PRICE_ASC   ProductOrderBy = 1
	ProductOrderBy_PRICE_DESC  ProductOrderBy = 2
)

// Enum value maps for ProductOrderBy.
var (
	ProductOrderBy_name = map[int32]string{
		0: "BEST_SELLER",
		1: "PRICE_ASC",
		2: "PRICE_DESC",
	}
	ProductOrderBy_value = map[string]int32{
		"BEST_SELLER": 0,
		"PRICE_ASC":   1,
		"PRICE_DESC":  2,
	}
)

func (x ProductOrderBy) Enum() *ProductOrderBy {
	p := new(ProductOrderBy)
	*p = x
	return p
}

func (x ProductOrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductOrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (ProductOrderBy) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x ProductOrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductOrderBy.Descriptor instead.
func (ProductOrderBy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

type LoadHomeScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHomeScreenRequest) Reset() {
	*x = LoadHomeScreenRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHomeScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHomeScreenRequest) ProtoMessage() {}

func (x *LoadHomeScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHomeScreenRequest.ProtoReflect.Descriptor instead.
func (*LoadHomeScreenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

type LoadHomeScreenResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BestsellerProducts []*Product             `protobuf:"bytes,1,rep,name=bestseller_products,json=bestsellerProducts,proto3" json:"bestseller_products,omitempty"`
	TopSearchProducts  []*Product             `protobuf:"bytes,2,rep,name=top_search_products,json=topSearchProducts,proto3" json:"top_search_products,omitempty"`
	Categories         []*Category            `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Brands             []*Brand               `protobuf:"bytes,4,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoadHomeScreenResponse) Reset() {
	*x = LoadHomeScreenResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHomeScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHomeScreenResponse) ProtoMessage() {}

func (x *LoadHomeScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHomeScreenResponse.ProtoReflect.Descriptor instead.
func (*LoadHomeScreenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *LoadHomeScreenResponse) GetBestsellerProducts() []*Product {
	if x != nil {
		return x.BestsellerProducts
	}
	return nil
}

func (x *LoadHomeScreenResponse) GetTopSearchProducts() []*Product {
	if x != nil {
		return x.TopSearchProducts
	}
	return nil
}

func (x *LoadHomeScreenResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *LoadHomeScreenResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

type PriceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRange) Reset() {
	*x = PriceRange{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRange) ProtoMessage() {}

func (x *PriceRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRange.ProtoReflect.Descriptor instead.
func (*PriceRange) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *PriceRange) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *PriceRange) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ProductFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceRange    *PriceRange            `protobuf:"bytes,1,opt,name=price_range,json=priceRange,proto3" json:"price_range,omitempty"`
	BrandIds      []int32                `protobuf:"varint,2,rep,packed,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFilter) Reset() {
	*x = ProductFilter{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFilter) ProtoMessage() {}

func (x *ProductFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFilter.ProtoReflect.Descriptor instead.
func (*ProductFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *ProductFilter) GetPriceRange() *PriceRange {
	if x != nil {
		return x.PriceRange
	}
	return nil
}

func (x *ProductFilter) GetBrandIds() []int32 {
	if x != nil {
		return x.BrandIds
	}
	return nil
}

type LoadProductsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Filter        *ProductFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       ProductOrderBy         `protobuf:"varint,3,opt,name=order_by,json=orderBy,proto3,enum=api.ProductOrderBy" json:"order_by,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProductsByCategoryRequest) Reset() {
	*x = LoadProductsByCategoryRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProductsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProductsByCategoryRequest) ProtoMessage() {}

func (x *LoadProductsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProductsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*LoadProductsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *LoadProductsByCategoryRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *LoadProductsByCategoryRequest) GetFilter() *ProductFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *LoadProductsByCategoryRequest) GetOrderBy() ProductOrderBy {
	if x != nil {
		return x.OrderBy
	}
	return ProductOrderBy_BEST_SELLER
}

func (x *LoadProductsByCategoryRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type LoadProductsByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Brands        []*Brand               `protobuf:"bytes,3,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProductsByCategoryResponse) Reset() {
	*x = LoadProductsByCategoryResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProductsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProductsByCategoryResponse) ProtoMessage() {}

func (x *LoadProductsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProductsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*LoadProductsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *LoadProductsByCategoryResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *LoadProductsByCategoryResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *LoadProductsByCategoryResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

type LoadProductDetailPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProductDetailPageRequest) Reset() {
	*x = LoadProductDetailPageRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProductDetailPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProductDetailPageRequest) ProtoMessage() {}

func (x *LoadProductDetailPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProductDetailPageRequest.ProtoReflect.Descriptor instead.
func (*LoadProductDetailPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *LoadProductDetailPageRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type LoadProductDetailPageResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Product                   *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	OtherSameCategoryProducts []*Product             `protobuf:"bytes,2,rep,name=other_same_category_products,json=otherSameCategoryProducts,proto3" json:"other_same_category_products,omitempty"` // Renamed for clarity
	OtherSameBrandProducts    []*Product             `protobuf:"bytes,3,rep,name=other_same_brand_products,json=otherSameBrandProducts,proto3" json:"other_same_brand_products,omitempty"`          // Renamed for clarity
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LoadProductDetailPageResponse) Reset() {
	*x = LoadProductDetailPageResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProductDetailPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProductDetailPageResponse) ProtoMessage() {}

func (x *LoadProductDetailPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProductDetailPageResponse.ProtoReflect.Descriptor instead.
func (*LoadProductDetailPageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *LoadProductDetailPageResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *LoadProductDetailPageResponse) GetOtherSameCategoryProducts() []*Product {
	if x != nil {
		return x.OtherSameCategoryProducts
	}
	return nil
}

func (x *LoadProductDetailPageResponse) GetOtherSameBrandProducts() []*Product {
	if x != nil {
		return x.OtherSameBrandProducts
	}
	return nil
}

type LoadProfileInfoPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProfileInfoPageRequest) Reset() {
	*x = LoadProfileInfoPageRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProfileInfoPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProfileInfoPageRequest) ProtoMessage() {}

func (x *LoadProfileInfoPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProfileInfoPageRequest.ProtoReflect.Descriptor instead.
func (*LoadProfileInfoPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

type LoadProfileInfoPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProfileInfoPageResponse) Reset() {
	*x = LoadProfileInfoPageResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProfileInfoPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProfileInfoPageResponse) ProtoMessage() {}

func (x *LoadProfileInfoPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProfileInfoPageResponse.ProtoReflect.Descriptor instead.
func (*LoadProfileInfoPageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *LoadProfileInfoPageResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoadUserOrderPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"` // Request pagination details for orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserOrderPageRequest) Reset() {
	*x = LoadUserOrderPageRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserOrderPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserOrderPageRequest) ProtoMessage() {}

func (x *LoadUserOrderPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserOrderPageRequest.ProtoReflect.Descriptor instead.
func (*LoadUserOrderPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *LoadUserOrderPageRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type LoadUserOrderPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserOrderPageResponse) Reset() {
	*x = LoadUserOrderPageResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserOrderPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserOrderPageResponse) ProtoMessage() {}

func (x *LoadUserOrderPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserOrderPageResponse.ProtoReflect.Descriptor instead.
func (*LoadUserOrderPageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *LoadUserOrderPageResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *LoadUserOrderPageResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type LoadCartPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCartPageRequest) Reset() {
	*x = LoadCartPageRequest{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCartPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCartPageRequest) ProtoMessage() {}

func (x *LoadCartPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCartPageRequest.ProtoReflect.Descriptor instead.
func (*LoadCartPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

type LoadCartPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CheckOutBill  float64                `protobuf:"fixed64,3,opt,name=check_out_bill,json=checkOutBill,proto3" json:"check_out_bill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCartPageResponse) Reset() {
	*x = LoadCartPageResponse{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCartPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCartPageResponse) ProtoMessage() {}

func (x *LoadCartPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCartPageResponse.ProtoReflect.Descriptor instead.
func (*LoadCartPageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *LoadCartPageResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LoadCartPageResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *LoadCartPageResponse) GetCheckOutBill() float64 {
	if x != nil {
		return x.CheckOutBill
	}
	return 0
}

type AddCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemRequest) Reset() {
	*x = AddCartItemRequest{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemRequest) ProtoMessage() {}

func (x *AddCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemRequest.ProtoReflect.Descriptor instead.
func (*AddCartItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *AddCartItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddCartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CartItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemResponse) Reset() {
	*x = AddCartItemResponse{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemResponse) ProtoMessage() {}

func (x *AddCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemResponse.ProtoReflect.Descriptor instead.
func (*AddCartItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *AddCartItemResponse) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartItemId    int32                  `protobuf:"varint,1,opt,name=cart_item_id,json=cartItemId,proto3" json:"cart_item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemRequest) Reset() {
	*x = UpdateCartItemRequest{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemRequest) ProtoMessage() {}

func (x *UpdateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCartItemRequest) GetCartItemId() int32 {
	if x != nil {
		return x.CartItemId
	}
	return 0
}

func (x *UpdateCartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CartItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemResponse) Reset() {
	*x = UpdateCartItemResponse{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemResponse) ProtoMessage() {}

func (x *UpdateCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateCartItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCartItemResponse) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartItemId    int32                  `protobuf:"varint,1,opt,name=cart_item_id,json=cartItemId,proto3" json:"cart_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemRequest) Reset() {
	*x = DeleteCartItemRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemRequest) ProtoMessage() {}

func (x *DeleteCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCartItemRequest) GetCartItemId() int32 {
	if x != nil {
		return x.CartItemId
	}
	return 0
}

type DeleteCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemResponse) Reset() {
	*x = DeleteCartItemResponse{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemResponse) ProtoMessage() {}

func (x *DeleteCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteCartItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\x1a\n" +
	"data.proto\"R\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\"Q\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.api.UserR\x04user\"\xa6\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\x122\n" +
	"\x10confirm_password\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fconfirmPassword\x12\x1b\n" +
	"\x04name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"\x12\n" +
	"\x10RegisterResponse\"\x17\n" +
	"\x15LoadHomeScreenRequest\"\xe8\x01\n" +
	"\x16LoadHomeScreenResponse\x12=\n" +
	"\x13bestseller_products\x18\x01 \x03(\v2\f.api.ProductR\x12bestsellerProducts\x12<\n" +
	"\x13top_search_products\x18\x02 \x03(\v2\f.api.ProductR\x11topSearchProducts\x12-\n" +
	"\n" +
	"categories\x18\x03 \x03(\v2\r.api.CategoryR\n" +
	"categories\x12\"\n" +
	"\x06brands\x18\x04 \x03(\v2\n" +
	".api.BrandR\x06brands\"0\n" +
	"\n" +
	"PriceRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\"^\n" +
	"\rProductFilter\x120\n" +
	"\vprice_range\x18\x01 \x01(\v2\x0f.api.PriceRangeR\n" +
	"priceRange\x12\x1b\n" +
	"\tbrand_ids\x18\x02 \x03(\x05R\bbrandIds\"\xd6\x01\n" +
	"\x1dLoadProductsByCategoryRequest\x12(\n" +
	"\vcategory_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\n" +
	"categoryId\x12*\n" +
	"\x06filter\x18\x02 \x01(\v2\x12.api.ProductFilterR\x06filter\x12.\n" +
	"\border_by\x18\x03 \x01(\x0e2\x13.api.ProductOrderByR\aorderBy\x12/\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\"\x9f\x01\n" +
	"\x1eLoadProductsByCategoryResponse\x12(\n" +
	"\bproducts\x18\x01 \x03(\v2\f.api.ProductR\bproducts\x12/\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\x12\"\n" +
	"\x06brands\x18\x03 \x03(\v2\n" +
	".api.BrandR\x06brands\"F\n" +
	"\x1cLoadProductDetailPageRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tproductId\"\xdf\x01\n" +
	"\x1dLoadProductDetailPageResponse\x12&\n" +
	"\aproduct\x18\x01 \x01(\v2\f.api.ProductR\aproduct\x12M\n" +
	"\x1cother_same_category_products\x18\x02 \x03(\v2\f.api.ProductR\x19otherSameCategoryProducts\x12G\n" +
	"\x19other_same_brand_products\x18\x03 \x03(\v2\f.api.ProductR\x16otherSameBrandProducts\"\x1c\n" +
	"\x1aLoadProfileInfoPageRequest\"<\n" +
	"\x1bLoadProfileInfoPageResponse\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.api.UserR\x04user\"K\n" +
	"\x18LoadUserOrderPageRequest\x12/\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\"p\n" +
	"\x19LoadUserOrderPageResponse\x12\"\n" +
	"\x06orders\x18\x01 \x03(\v2\n" +
	".api.OrderR\x06orders\x12/\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x0f.api.PaginationR\n" +
	"pagination\"\x15\n" +
	"\x13LoadCartPageRequest\"\x82\x01\n" +
	"\x14LoadCartPageResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.api.CartItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice\x12$\n" +
	"\x0echeck_out_bill\x18\x03 \x01(\x01R\fcheckOutBill\"a\n" +
	"\x12AddCartItemRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bquantity\"8\n" +
	"\x13AddCartItemResponse\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.api.CartItemR\x04item\"g\n" +
	"\x15UpdateCartItemRequest\x12)\n" +
	"\fcart_item_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\n" +
	"cartItemId\x12#\n" +
	"\bquantity\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bquantity\";\n" +
	"\x16UpdateCartItemResponse\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.api.CartItemR\x04item\"B\n" +
	"\x15DeleteCartItemRequest\x12)\n" +
	"\fcart_item_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\n" +
	"cartItemId\"\x18\n" +
	"\x16DeleteCartItemResponse*@\n" +
	"\x0eProductOrderBy\x12\x0f\n" +
	"\vBEST_SELLER\x10\x00\x12\r\n" +
	"\tPRICE_ASC\x10\x01\x12\x0e\n" +
	"\n" +
	"PRICE_DESC\x10\x022\x9a\t\n" +
	"\aService\x12E\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/login\x12Q\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/register\x12\\\n" +
	"\x0eLoadHomeScreen\x12\x1a.api.LoadHomeScreenRequest\x1a\x1b.api.LoadHomeScreenResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/home\x12\x91\x01\n" +
	"\x16LoadProductsByCategory\x12\".api.LoadProductsByCategoryRequest\x1a#.api.LoadProductsByCategoryResponse\".\x82\xd3\xe4\x93\x02(\x12&/api/categories/{category_id}/products\x12\x82\x01\n" +
	"\x15LoadProductDetailPage\x12!.api.LoadProductDetailPageRequest\x1a\".api.LoadProductDetailPageResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/products/{product_id}\x12n\n" +
	"\x13LoadProfileInfoPage\x12\x1f.api.LoadProfileInfoPageRequest\x1a .api.LoadProfileInfoPageResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/profile\x12o\n" +
	"\x11LoadUserOrderPage\x12\x1d.api.LoadUserOrderPageRequest\x1a\x1e.api.LoadUserOrderPageResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/orders_history\x12V\n" +
	"\fLoadCartPage\x12\x18.api.LoadCartPageRequest\x1a\x19.api.LoadCartPageResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/cart\x12\\\n" +
	"\vAddCartItem\x12\x17.api.AddCartItemRequest\x1a\x18.api.AddCartItemResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/cart/items\x12t\n" +
	"\x0eUpdateCartItem\x12\x1a.api.UpdateCartItemRequest\x1a\x1b.api.UpdateCartItemResponse\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/api/cart/items/{cart_item_id}\x12q\n" +
	"\x0eDeleteCartItem\x12\x1a.api.DeleteCartItemRequest\x1a\x1b.api.DeleteCartItemResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/api/cart/items/{cart_item_id}B3Z1github.com/linhhuynhcoding/web-my-pham/server/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_goTypes = []any{
	(ProductOrderBy)(0),                    // 0: api.ProductOrderBy
	(*LoginRequest)(nil),                   // 1: api.LoginRequest
	(*LoginResponse)(nil),                  // 2: api.LoginResponse
	(*RegisterRequest)(nil),                // 3: api.RegisterRequest
	(*RegisterResponse)(nil),               // 4: api.RegisterResponse
	(*LoadHomeScreenRequest)(nil),          // 5: api.LoadHomeScreenRequest
	(*LoadHomeScreenResponse)(nil),         // 6: api.LoadHomeScreenResponse
	(*PriceRange)(nil),                     // 7: api.PriceRange
	(*ProductFilter)(nil),                  // 8: api.ProductFilter
	(*LoadProductsByCategoryRequest)(nil),  // 9: api.LoadProductsByCategoryRequest
	(*LoadProductsByCategoryResponse)(nil), // 10: api.LoadProductsByCategoryResponse
	(*LoadProductDetailPageRequest)(nil),   // 11: api.LoadProductDetailPageRequest
	(*LoadProductDetailPageResponse)(nil),  // 12: api.LoadProductDetailPageResponse
	(*LoadProfileInfoPageRequest)(nil),     // 13: api.LoadProfileInfoPageRequest
	(*LoadProfileInfoPageResponse)(nil),    // 14: api.LoadProfileInfoPageResponse
	(*LoadUserOrderPageRequest)(nil),       // 15: api.LoadUserOrderPageRequest
	(*LoadUserOrderPageResponse)(nil),      // 16: api.LoadUserOrderPageResponse
	(*LoadCartPageRequest)(nil),            // 17: api.LoadCartPageRequest
	(*LoadCartPageResponse)(nil),           // 18: api.LoadCartPageResponse
	(*AddCartItemRequest)(nil),             // 19: api.AddCartItemRequest
	(*AddCartItemResponse)(nil),            // 20: api.AddCartItemResponse
	(*UpdateCartItemRequest)(nil),          // 21: api.UpdateCartItemRequest
	(*UpdateCartItemResponse)(nil),         // 22: api.UpdateCartItemResponse
	(*DeleteCartItemRequest)(nil),          // 23: api.DeleteCartItemRequest
	(*DeleteCartItemResponse)(nil),         // 24: api.DeleteCartItemResponse
	(*User)(nil),                           // 25: api.User
	(*Product)(nil),                        // 26: api.Product
	(*Category)(nil),                       // 27: api.Category
	(*Brand)(nil),                          // 28: api.Brand
	(*Pagination)(nil),                     // 29: api.Pagination
	(*Order)(nil),                          // 30: api.Order
	(*CartItem)(nil),                       // 31: api.CartItem
}
var file_api_proto_depIdxs = []int32{
	25, // 0: api.LoginResponse.user:type_name -> api.User
	26, // 1: api.LoadHomeScreenResponse.bestseller_products:type_name -> api.Product
	26, // 2: api.LoadHomeScreenResponse.top_search_products:type_name -> api.Product
	27, // 3: api.LoadHomeScreenResponse.categories:type_name -> api.Category
	28, // 4: api.LoadHomeScreenResponse.brands:type_name -> api.Brand
	7,  // 5: api.ProductFilter.price_range:type_name -> api.PriceRange
	8,  // 6: api.LoadProductsByCategoryRequest.filter:type_name -> api.ProductFilter
	0,  // 7: api.LoadProductsByCategoryRequest.order_by:type_name -> api.ProductOrderBy
	29, // 8: api.LoadProductsByCategoryRequest.pagination:type_name -> api.Pagination
	26, // 9: api.LoadProductsByCategoryResponse.products:type_name -> api.Product
	29, // 10: api.LoadProductsByCategoryResponse.pagination:type_name -> api.Pagination
	28, // 11: api.LoadProductsByCategoryResponse.brands:type_name -> api.Brand
	26, // 12: api.LoadProductDetailPageResponse.product:type_name -> api.Product
	26, // 13: api.LoadProductDetailPageResponse.other_same_category_products:type_name -> api.Product
	26, // 14: api.LoadProductDetailPageResponse.other_same_brand_products:type_name -> api.Product
	25, // 15: api.LoadProfileInfoPageResponse.user:type_name -> api.User
	29, // 16: api.LoadUserOrderPageRequest.pagination:type_name -> api.Pagination
	30, // 17: api.LoadUserOrderPageResponse.orders:type_name -> api.Order
	29, // 18: api.LoadUserOrderPageResponse.pagination:type_name -> api.Pagination
	31, // 19: api.LoadCartPageResponse.items:type_name -> api.CartItem
	31, // 20: api.AddCartItemResponse.item:type_name -> api.CartItem
	31, // 21: api.UpdateCartItemResponse.item:type_name -> api.CartItem
	1,  // 22: api.Service.Login:input_type -> api.LoginRequest
	3,  // 23: api.Service.Register:input_type -> api.RegisterRequest
	5,  // 24: api.Service.LoadHomeScreen:input_type -> api.LoadHomeScreenRequest
	9,  // 25: api.Service.LoadProductsByCategory:input_type -> api.LoadProductsByCategoryRequest
	11, // 26: api.Service.LoadProductDetailPage:input_type -> api.LoadProductDetailPageRequest
	13, // 27: api.Service.LoadProfileInfoPage:input_type -> api.LoadProfileInfoPageRequest
	15, // 28: api.Service.LoadUserOrderPage:input_type -> api.LoadUserOrderPageRequest
	17, // 29: api.Service.LoadCartPage:input_type -> api.LoadCartPageRequest
	19, // 30: api.Service.AddCartItem:input_type -> api.AddCartItemRequest
	21, // 31: api.Service.UpdateCartItem:input_type -> api.UpdateCartItemRequest
	23, // 32: api.Service.DeleteCartItem:input_type -> api.DeleteCartItemRequest
	2,  // 33: api.Service.Login:output_type -> api.LoginResponse
	4,  // 34: api.Service.Register:output_type -> api.RegisterResponse
	6,  // 35: api.Service.LoadHomeScreen:output_type -> api.LoadHomeScreenResponse
	10, // 36: api.Service.LoadProductsByCategory:output_type -> api.LoadProductsByCategoryResponse
	12, // 37: api.Service.LoadProductDetailPage:output_type -> api.LoadProductDetailPageResponse
	14, // 38: api.Service.LoadProfileInfoPage:output_type -> api.LoadProfileInfoPageResponse
	16, // 39: api.Service.LoadUserOrderPage:output_type -> api.LoadUserOrderPageResponse
	18, // 40: api.Service.LoadCartPage:output_type -> api.LoadCartPageResponse
	20, // 41: api.Service.AddCartItem:output_type -> api.AddCartItemResponse
	22, // 42: api.Service.UpdateCartItem:output_type -> api.UpdateCartItemResponse
	24, // 43: api.Service.DeleteCartItem:output_type -> api.DeleteCartItemResponse
	33, // [33:44] is the sub-list for method output_type
	22, // [22:33] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
