// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_Login_FullMethodName                  = "/api.Service/Login"
	Service_Register_FullMethodName               = "/api.Service/Register"
	Service_LoadHomeScreen_FullMethodName         = "/api.Service/LoadHomeScreen"
	Service_LoadProductsByCategory_FullMethodName = "/api.Service/LoadProductsByCategory"
	Service_LoadProductDetailPage_FullMethodName  = "/api.Service/LoadProductDetailPage"
	Service_LoadProfileInfoPage_FullMethodName    = "/api.Service/LoadProfileInfoPage"
	Service_LoadUserOrderPage_FullMethodName      = "/api.Service/LoadUserOrderPage"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// Login
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Register
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Load Home Screen
	LoadHomeScreen(ctx context.Context, in *LoadHomeScreenRequest, opts ...grpc.CallOption) (*LoadHomeScreenResponse, error)
	// Load Products by Category
	LoadProductsByCategory(ctx context.Context, in *LoadProductsByCategoryRequest, opts ...grpc.CallOption) (*LoadProductsByCategoryResponse, error)
	// Load Product Detail Page
	LoadProductDetailPage(ctx context.Context, in *LoadProductDetailPageRequest, opts ...grpc.CallOption) (*LoadProductDetailPageResponse, error)
	// Load Profile Info Page
	LoadProfileInfoPage(ctx context.Context, in *LoadProfileInfoPageRequest, opts ...grpc.CallOption) (*LoadProfileInfoPageResponse, error)
	// Load User Order Page
	LoadUserOrderPage(ctx context.Context, in *LoadUserOrderPageRequest, opts ...grpc.CallOption) (*LoadUserOrderPageResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Service_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Service_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LoadHomeScreen(ctx context.Context, in *LoadHomeScreenRequest, opts ...grpc.CallOption) (*LoadHomeScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadHomeScreenResponse)
	err := c.cc.Invoke(ctx, Service_LoadHomeScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LoadProductsByCategory(ctx context.Context, in *LoadProductsByCategoryRequest, opts ...grpc.CallOption) (*LoadProductsByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadProductsByCategoryResponse)
	err := c.cc.Invoke(ctx, Service_LoadProductsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LoadProductDetailPage(ctx context.Context, in *LoadProductDetailPageRequest, opts ...grpc.CallOption) (*LoadProductDetailPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadProductDetailPageResponse)
	err := c.cc.Invoke(ctx, Service_LoadProductDetailPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LoadProfileInfoPage(ctx context.Context, in *LoadProfileInfoPageRequest, opts ...grpc.CallOption) (*LoadProfileInfoPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadProfileInfoPageResponse)
	err := c.cc.Invoke(ctx, Service_LoadProfileInfoPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LoadUserOrderPage(ctx context.Context, in *LoadUserOrderPageRequest, opts ...grpc.CallOption) (*LoadUserOrderPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadUserOrderPageResponse)
	err := c.cc.Invoke(ctx, Service_LoadUserOrderPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// Login
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Register
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Load Home Screen
	LoadHomeScreen(context.Context, *LoadHomeScreenRequest) (*LoadHomeScreenResponse, error)
	// Load Products by Category
	LoadProductsByCategory(context.Context, *LoadProductsByCategoryRequest) (*LoadProductsByCategoryResponse, error)
	// Load Product Detail Page
	LoadProductDetailPage(context.Context, *LoadProductDetailPageRequest) (*LoadProductDetailPageResponse, error)
	// Load Profile Info Page
	LoadProfileInfoPage(context.Context, *LoadProfileInfoPageRequest) (*LoadProfileInfoPageResponse, error)
	// Load User Order Page
	LoadUserOrderPage(context.Context, *LoadUserOrderPageRequest) (*LoadUserOrderPageResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedServiceServer) LoadHomeScreen(context.Context, *LoadHomeScreenRequest) (*LoadHomeScreenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadHomeScreen not implemented")
}
func (UnimplementedServiceServer) LoadProductsByCategory(context.Context, *LoadProductsByCategoryRequest) (*LoadProductsByCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadProductsByCategory not implemented")
}
func (UnimplementedServiceServer) LoadProductDetailPage(context.Context, *LoadProductDetailPageRequest) (*LoadProductDetailPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadProductDetailPage not implemented")
}
func (UnimplementedServiceServer) LoadProfileInfoPage(context.Context, *LoadProfileInfoPageRequest) (*LoadProfileInfoPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadProfileInfoPage not implemented")
}
func (UnimplementedServiceServer) LoadUserOrderPage(context.Context, *LoadUserOrderPageRequest) (*LoadUserOrderPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadUserOrderPage not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LoadHomeScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadHomeScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadHomeScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadHomeScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadHomeScreen(ctx, req.(*LoadHomeScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LoadProductsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadProductsByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadProductsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadProductsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadProductsByCategory(ctx, req.(*LoadProductsByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LoadProductDetailPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadProductDetailPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadProductDetailPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadProductDetailPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadProductDetailPage(ctx, req.(*LoadProductDetailPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LoadProfileInfoPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadProfileInfoPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadProfileInfoPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadProfileInfoPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadProfileInfoPage(ctx, req.(*LoadProfileInfoPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LoadUserOrderPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadUserOrderPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LoadUserOrderPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LoadUserOrderPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LoadUserOrderPage(ctx, req.(*LoadUserOrderPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Service_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Service_Register_Handler,
		},
		{
			MethodName: "LoadHomeScreen",
			Handler:    _Service_LoadHomeScreen_Handler,
		},
		{
			MethodName: "LoadProductsByCategory",
			Handler:    _Service_LoadProductsByCategory_Handler,
		},
		{
			MethodName: "LoadProductDetailPage",
			Handler:    _Service_LoadProductDetailPage_Handler,
		},
		{
			MethodName: "LoadProfileInfoPage",
			Handler:    _Service_LoadProfileInfoPage_Handler,
		},
		{
			MethodName: "LoadUserOrderPage",
			Handler:    _Service_LoadUserOrderPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
