// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brands.sql

package repository

import (
	"context"
)

const getBrands = `-- name: GetBrands :many
select id, name, image_url from brands
`

func (q *Queries) GetBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, getBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(&i.ID, &i.Name, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
