// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserCart = `-- name: CreateUserCart :exec
insert into carts (user_id) values ($1)
`

func (q *Queries) CreateUserCart(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, createUserCart, userID)
	return err
}
