// Code generated by go:generate; DO NOT EDIT.
package repository

import "github.com/jackc/pgx/v5/pgtype"

func (x GetProductByBrandIDParams) GetBrandID() int32 { return x.BrandID }

func (x GetProductByBrandIDParams) GetLimit() int32 { return x.Limit }

func (x GetProductByBrandIDParams) GetOffset() int32 { return x.Offset }

func (x GetProductByBrandIDRow) GetID() int32 { return x.ID }

func (x GetProductByBrandIDRow) GetName() string { return x.Name }

func (x GetProductByBrandIDRow) GetDescription() pgtype.Text { return x.Description }

func (x GetProductByBrandIDRow) GetPrice() pgtype.Numeric { return x.Price }

func (x GetProductByBrandIDRow) GetCategoryID() int32 { return x.CategoryID }

func (x GetProductByBrandIDRow) GetStock() int32 { return x.Stock }

func (x GetProductByBrandIDRow) GetBuyturn() int32 { return x.Buyturn }

func (x GetProductByBrandIDRow) GetImageUrl() string { return x.ImageUrl }

func (x GetProductByBrandIDRow) GetBrandID() int32 { return x.BrandID }

func (x GetProductByBrandIDRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetProductByBrandIDRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetProductByBrandIDRow) GetBrandID_2() pgtype.Int4 { return x.BrandID_2 }

func (x GetProductByBrandIDRow) GetBrandName() pgtype.Text { return x.BrandName }

func (x GetProductByBrandIDRow) GetBrandImageUrl() pgtype.Text { return x.BrandImageUrl }

func (x GetProductByBrandIDRow) GetCategoryName() pgtype.Text { return x.CategoryName }

func (x GetProductByBrandIDRow) GetCategoryID_2() pgtype.Int4 { return x.CategoryID_2 }

func (x GetProductByBrandIDRow) GetCategoryImageUrl() pgtype.Text { return x.CategoryImageUrl }

func (x GetProductByCategoryIDBasicParams) GetLimit() int32 { return x.Limit }

func (x GetProductByCategoryIDBasicParams) GetOffset() int32 { return x.Offset }

func (x GetProductByCategoryIDBasicRow) GetID() int32 { return x.ID }

func (x GetProductByCategoryIDBasicRow) GetName() string { return x.Name }

func (x GetProductByCategoryIDBasicRow) GetDescription() pgtype.Text { return x.Description }

func (x GetProductByCategoryIDBasicRow) GetPrice() pgtype.Numeric { return x.Price }

func (x GetProductByCategoryIDBasicRow) GetCategoryID() int32 { return x.CategoryID }

func (x GetProductByCategoryIDBasicRow) GetStock() int32 { return x.Stock }

func (x GetProductByCategoryIDBasicRow) GetBuyturn() int32 { return x.Buyturn }

func (x GetProductByCategoryIDBasicRow) GetImageUrl() string { return x.ImageUrl }

func (x GetProductByCategoryIDBasicRow) GetBrandID() int32 { return x.BrandID }

func (x GetProductByCategoryIDBasicRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetProductByCategoryIDBasicRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetProductByCategoryIDBasicRow) GetBrandID_2() pgtype.Int4 { return x.BrandID_2 }

func (x GetProductByCategoryIDBasicRow) GetBrandName() pgtype.Text { return x.BrandName }

func (x GetProductByCategoryIDBasicRow) GetBrandImageUrl() pgtype.Text { return x.BrandImageUrl }

func (x GetProductByCategoryIDBasicRow) GetCategoryName() pgtype.Text { return x.CategoryName }

func (x GetProductByCategoryIDBasicRow) GetCategoryID_2() pgtype.Int4 { return x.CategoryID_2 }

func (x GetProductByCategoryIDBasicRow) GetCategoryImageUrl() pgtype.Text { return x.CategoryImageUrl }

func (x GetProductByIDRow) GetID() int32 { return x.ID }

func (x GetProductByIDRow) GetName() string { return x.Name }

func (x GetProductByIDRow) GetDescription() pgtype.Text { return x.Description }

func (x GetProductByIDRow) GetPrice() pgtype.Numeric { return x.Price }

func (x GetProductByIDRow) GetCategoryID() int32 { return x.CategoryID }

func (x GetProductByIDRow) GetStock() int32 { return x.Stock }

func (x GetProductByIDRow) GetBuyturn() int32 { return x.Buyturn }

func (x GetProductByIDRow) GetImageUrl() string { return x.ImageUrl }

func (x GetProductByIDRow) GetBrandID() int32 { return x.BrandID }

func (x GetProductByIDRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetProductByIDRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetProductByIDRow) GetBrandID_2() pgtype.Int4 { return x.BrandID_2 }

func (x GetProductByIDRow) GetBrandName() pgtype.Text { return x.BrandName }

func (x GetProductByIDRow) GetBrandImageUrl() pgtype.Text { return x.BrandImageUrl }

func (x GetProductByIDRow) GetCategoryName() pgtype.Text { return x.CategoryName }

func (x GetProductByIDRow) GetCategoryID_2() pgtype.Int4 { return x.CategoryID_2 }

func (x GetProductByIDRow) GetCategoryImageUrl() pgtype.Text { return x.CategoryImageUrl }

