// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: load_product_detail_page.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByBrandID = `-- name: GetProductByBrandID :many
select 
    p.id, p.name, p.description, p.price, p.category_id, p.stock, p.buyturn, p.image_url, p.brand_id, p.created_at, p.updated_at, 
    b.id as brand_id,
    b.name as brand_name, 
    b.image_url as brand_image_url,
    c.name as category_name, 
    c.id as category_id,
    c.image_url as category_image_url
from products p
left join brands b on p.brand_id = b.id
left join categories c on c.id = p.category_id
where p.brand_id = $1 
order by p.buyturn desc
limit $2 offset $3
`

type GetProductByBrandIDParams struct {
	BrandID int32 `json:"brand_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type GetProductByBrandIDRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Price            pgtype.Numeric   `json:"price"`
	CategoryID       int32            `json:"category_id"`
	Stock            int32            `json:"stock"`
	Buyturn          int32            `json:"buyturn"`
	ImageUrl         string           `json:"image_url"`
	BrandID          int32            `json:"brand_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	BrandID_2        pgtype.Int4      `json:"brand_id_2"`
	BrandName        pgtype.Text      `json:"brand_name"`
	BrandImageUrl    pgtype.Text      `json:"brand_image_url"`
	CategoryName     pgtype.Text      `json:"category_name"`
	CategoryID_2     pgtype.Int4      `json:"category_id_2"`
	CategoryImageUrl pgtype.Text      `json:"category_image_url"`
}

func (q *Queries) GetProductByBrandID(ctx context.Context, arg GetProductByBrandIDParams) ([]GetProductByBrandIDRow, error) {
	rows, err := q.db.Query(ctx, getProductByBrandID, arg.BrandID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductByBrandIDRow{}
	for rows.Next() {
		var i GetProductByBrandIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.Stock,
			&i.Buyturn,
			&i.ImageUrl,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandID_2,
			&i.BrandName,
			&i.BrandImageUrl,
			&i.CategoryName,
			&i.CategoryID_2,
			&i.CategoryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByCategoryIDBasic = `-- name: GetProductByCategoryIDBasic :many
select 
    p.id, p.name, p.description, p.price, p.category_id, p.stock, p.buyturn, p.image_url, p.brand_id, p.created_at, p.updated_at, 
    b.id as brand_id,
    b.name as brand_name, 
    b.image_url as brand_image_url,
    c.name as category_name, 
    c.id as category_id,
    c.image_url as category_image_url
from products p
left join brands b on brands.id = p.brand_id
left join categories c on categories.id = p.category_id
where p.category_id = $1
order by buyturn desc
limit $1 offset $2
`

type GetProductByCategoryIDBasicParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetProductByCategoryIDBasicRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Price            pgtype.Numeric   `json:"price"`
	CategoryID       int32            `json:"category_id"`
	Stock            int32            `json:"stock"`
	Buyturn          int32            `json:"buyturn"`
	ImageUrl         string           `json:"image_url"`
	BrandID          int32            `json:"brand_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	BrandID_2        pgtype.Int4      `json:"brand_id_2"`
	BrandName        pgtype.Text      `json:"brand_name"`
	BrandImageUrl    pgtype.Text      `json:"brand_image_url"`
	CategoryName     pgtype.Text      `json:"category_name"`
	CategoryID_2     pgtype.Int4      `json:"category_id_2"`
	CategoryImageUrl pgtype.Text      `json:"category_image_url"`
}

func (q *Queries) GetProductByCategoryIDBasic(ctx context.Context, arg GetProductByCategoryIDBasicParams) ([]GetProductByCategoryIDBasicRow, error) {
	rows, err := q.db.Query(ctx, getProductByCategoryIDBasic, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductByCategoryIDBasicRow{}
	for rows.Next() {
		var i GetProductByCategoryIDBasicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.Stock,
			&i.Buyturn,
			&i.ImageUrl,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandID_2,
			&i.BrandName,
			&i.BrandImageUrl,
			&i.CategoryName,
			&i.CategoryID_2,
			&i.CategoryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
select 
    p.id, p.name, p.description, p.price, p.category_id, p.stock, p.buyturn, p.image_url, p.brand_id, p.created_at, p.updated_at, 
    b.id as brand_id,
    b.name as brand_name, 
    b.image_url as brand_image_url,
    c.name as category_name, 
    c.id as category_id,
    c.image_url as category_image_url
from products p
left join brands b on b.id = p.brand_id
left join categories c on c.id = p.category_id
where p.id = $1
`

type GetProductByIDRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Price            pgtype.Numeric   `json:"price"`
	CategoryID       int32            `json:"category_id"`
	Stock            int32            `json:"stock"`
	Buyturn          int32            `json:"buyturn"`
	ImageUrl         string           `json:"image_url"`
	BrandID          int32            `json:"brand_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	BrandID_2        pgtype.Int4      `json:"brand_id_2"`
	BrandName        pgtype.Text      `json:"brand_name"`
	BrandImageUrl    pgtype.Text      `json:"brand_image_url"`
	CategoryName     pgtype.Text      `json:"category_name"`
	CategoryID_2     pgtype.Int4      `json:"category_id_2"`
	CategoryImageUrl pgtype.Text      `json:"category_image_url"`
}

func (q *Queries) GetProductByID(ctx context.Context, id int32) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.Stock,
		&i.Buyturn,
		&i.ImageUrl,
		&i.BrandID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandID_2,
		&i.BrandName,
		&i.BrandImageUrl,
		&i.CategoryName,
		&i.CategoryID_2,
		&i.CategoryImageUrl,
	)
	return i, err
}
