// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: load_home_screen.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBestSellerProducts = `-- name: GetBestSellerProducts :many
select 
    p.id, p.name, p.description, p.price, p.category_id, p.stock, p.buyturn, p.image_url, p.brand_id, p.created_at, p.updated_at, 
    brands.id as brand_id,
    brands.name as brand_name, 
    brands.image_url as brand_image_url,
    categories.name as category_name, 
    categories.id as category_id,
    categories.image_url as category_image_url
from products p
left join brands on brands.id = p.brand_id
left join categories on categories.id = p.category_id
where p.stock > 0
order by p.buyturn desc
limit $1
`

type GetBestSellerProductsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Price            pgtype.Numeric   `json:"price"`
	CategoryID       int32            `json:"category_id"`
	Stock            int32            `json:"stock"`
	Buyturn          int32            `json:"buyturn"`
	ImageUrl         string           `json:"image_url"`
	BrandID          int32            `json:"brand_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	BrandID_2        pgtype.Int4      `json:"brand_id_2"`
	BrandName        pgtype.Text      `json:"brand_name"`
	BrandImageUrl    pgtype.Text      `json:"brand_image_url"`
	CategoryName     pgtype.Text      `json:"category_name"`
	CategoryID_2     pgtype.Int4      `json:"category_id_2"`
	CategoryImageUrl pgtype.Text      `json:"category_image_url"`
}

// order by buyturn
// stock > 0
// limit $1
func (q *Queries) GetBestSellerProducts(ctx context.Context, limit int32) ([]GetBestSellerProductsRow, error) {
	rows, err := q.db.Query(ctx, getBestSellerProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBestSellerProductsRow{}
	for rows.Next() {
		var i GetBestSellerProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.Stock,
			&i.Buyturn,
			&i.ImageUrl,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandID_2,
			&i.BrandName,
			&i.BrandImageUrl,
			&i.CategoryName,
			&i.CategoryID_2,
			&i.CategoryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
