// Code generated by go:generate; DO NOT EDIT.
package repository

import "github.com/jackc/pgx/v5/pgtype"

func (x GetProductByCategoryIDParams) GetLimit() int32 { return x.Limit }

func (x GetProductByCategoryIDParams) GetOffset() int32 { return x.Offset }

func (x GetProductByCategoryIDParams) GetPriceMin() interface{} { return x.PriceMin }

func (x GetProductByCategoryIDParams) GetPriceMax() interface{} { return x.PriceMax }

func (x GetProductByCategoryIDParams) GetCategoryID() int32 { return x.CategoryID }

func (x GetProductByCategoryIDParams) GetBrandID() interface{} { return x.BrandID }

func (x GetProductByCategoryIDParams) GetSortBy() interface{} { return x.SortBy }

func (x GetProductByCategoryIDRow) GetID() int32 { return x.ID }

func (x GetProductByCategoryIDRow) GetName() string { return x.Name }

func (x GetProductByCategoryIDRow) GetDescription() pgtype.Text { return x.Description }

func (x GetProductByCategoryIDRow) GetPrice() pgtype.Numeric { return x.Price }

func (x GetProductByCategoryIDRow) GetCategoryID() int32 { return x.CategoryID }

func (x GetProductByCategoryIDRow) GetStock() int32 { return x.Stock }

func (x GetProductByCategoryIDRow) GetBuyturn() int32 { return x.Buyturn }

func (x GetProductByCategoryIDRow) GetImageUrl() string { return x.ImageUrl }

func (x GetProductByCategoryIDRow) GetBrandID() int32 { return x.BrandID }

func (x GetProductByCategoryIDRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetProductByCategoryIDRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetProductByCategoryIDRow) GetBrandID_2() pgtype.Int4 { return x.BrandID_2 }

func (x GetProductByCategoryIDRow) GetBrandName() pgtype.Text { return x.BrandName }

func (x GetProductByCategoryIDRow) GetBrandImageUrl() pgtype.Text { return x.BrandImageUrl }

func (x GetProductByCategoryIDRow) GetCategoryName() pgtype.Text { return x.CategoryName }

func (x GetProductByCategoryIDRow) GetCategoryID_2() pgtype.Int4 { return x.CategoryID_2 }

func (x GetProductByCategoryIDRow) GetCategoryImageUrl() pgtype.Text { return x.CategoryImageUrl }

func (x GetProductByCategoryIDRow) GetTotal() *int64 { return x.Total }

