// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: load_product_cate_page.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByCategoryID = `-- name: GetProductByCategoryID :many
WITH res AS (
  SELECT
    p.id, p.name, p.description, p.price, p.category_id, p.stock, p.buyturn, p.image_url, p.brand_id, p.created_at, p.updated_at,
    b.name AS brand_name,
    b.image_url AS brand_image_url,
    c.name AS category_name,
    c.image_url AS category_image_url
  FROM products p
  LEFT JOIN brands b ON b.id = p.brand_id
  LEFT JOIN categories c ON c.id = p.category_id
  WHERE
    (
      $4::decimal(10,2) IS NULL
      OR $5::decimal(10,2) IS NULL
      OR p.price BETWEEN $4::decimal(10,2)
                    AND $5::decimal(10,2)
    )
    AND p.category_id = $6
    AND p.stock > 0
    AND (
      $7::int[] IS NULL
      OR array_length($7::int[], 1) = 0
      OR p.brand_id = ANY($7::int[])
    )
)
SELECT
  id, name, description, price, category_id, stock, buyturn, image_url, brand_id, created_at, updated_at, brand_name, brand_image_url, category_name, category_image_url,
  COUNT(*) OVER() AS total
FROM res
ORDER BY
  CASE $1
    WHEN 'price_asc'  THEN res.price
  END ASC,
  CASE $1
    WHEN 'price_desc' THEN res.price
  END DESC,
  CASE $1
    WHEN 'buyturn'    THEN res.buyturn
  END DESC
LIMIT $3 OFFSET $2
`

type GetProductByCategoryIDParams struct {
	SortBy     interface{}    `json:"sort_by"`
	Offset     int32          `json:"offset"`
	Limit      int32          `json:"limit"`
	PriceMin   pgtype.Numeric `json:"price_min"`
	PriceMax   pgtype.Numeric `json:"price_max"`
	CategoryID int32          `json:"category_id"`
	BrandID    []int32        `json:"brand_id"`
}

type GetProductByCategoryIDRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Price            pgtype.Numeric   `json:"price"`
	CategoryID       int32            `json:"category_id"`
	Stock            int32            `json:"stock"`
	Buyturn          int32            `json:"buyturn"`
	ImageUrl         string           `json:"image_url"`
	BrandID          int32            `json:"brand_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	BrandName        pgtype.Text      `json:"brand_name"`
	BrandImageUrl    pgtype.Text      `json:"brand_image_url"`
	CategoryName     pgtype.Text      `json:"category_name"`
	CategoryImageUrl pgtype.Text      `json:"category_image_url"`
	Total            *int64           `json:"total"`
}

func (q *Queries) GetProductByCategoryID(ctx context.Context, arg GetProductByCategoryIDParams) ([]GetProductByCategoryIDRow, error) {
	rows, err := q.db.Query(ctx, getProductByCategoryID,
		arg.SortBy,
		arg.Offset,
		arg.Limit,
		arg.PriceMin,
		arg.PriceMax,
		arg.CategoryID,
		arg.BrandID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductByCategoryIDRow{}
	for rows.Next() {
		var i GetProductByCategoryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.Stock,
			&i.Buyturn,
			&i.ImageUrl,
			&i.BrandID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandImageUrl,
			&i.CategoryName,
			&i.CategoryImageUrl,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
