// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: load_checkout_page.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchProductToCheckout = `-- name: FetchProductToCheckout :many
SELECT
    ci.id,
    ci.quantity,
    p.id as product_id,
    p.name as product_name,
    p.image_url as product_image_url,
    p.price as product_price
FROM
    cart_items ci
    JOIN products p ON ci.product_id = p.id
WHERE
    ci.id = ANY($1::int[])
`

type FetchProductToCheckoutRow struct {
	ID              int32          `json:"id"`
	Quantity        pgtype.Int4    `json:"quantity"`
	ProductID       int32          `json:"product_id"`
	ProductName     string         `json:"product_name"`
	ProductImageUrl string         `json:"product_image_url"`
	ProductPrice    pgtype.Numeric `json:"product_price"`
}

func (q *Queries) FetchProductToCheckout(ctx context.Context, Items []int32) ([]FetchProductToCheckoutRow, error) {
	rows, err := q.db.Query(ctx, fetchProductToCheckout, Items)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchProductToCheckoutRow{}
	for rows.Next() {
		var i FetchProductToCheckoutRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.ProductID,
			&i.ProductName,
			&i.ProductImageUrl,
			&i.ProductPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
