// Code generated by go:generate; DO NOT EDIT.
package repository

import "github.com/jackc/pgx/v5/pgtype"

func (x GetOrderHistoryByUserEmailParams) GetUserEmail() string { return x.UserEmail }

func (x GetOrderHistoryByUserEmailParams) GetLimit() int32 { return x.Limit }

func (x GetOrderHistoryByUserEmailParams) GetOffset() int32 { return x.Offset }

func (x GetOrderHistoryByUserEmailRow) GetID() int32 { return x.ID }

func (x GetOrderHistoryByUserEmailRow) GetUserEmail() string { return x.UserEmail }

func (x GetOrderHistoryByUserEmailRow) GetTotalPrice() pgtype.Numeric { return x.TotalPrice }

func (x GetOrderHistoryByUserEmailRow) GetStatus() string { return x.Status }

func (x GetOrderHistoryByUserEmailRow) GetShippingAddress() string { return x.ShippingAddress }

func (x GetOrderHistoryByUserEmailRow) GetPhone() string { return x.Phone }

func (x GetOrderHistoryByUserEmailRow) GetPaymentMethod() string { return x.PaymentMethod }

func (x GetOrderHistoryByUserEmailRow) GetOrderDate() pgtype.Date { return x.OrderDate }

func (x GetOrderHistoryByUserEmailRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetOrderHistoryByUserEmailRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetOrderHistoryByUserEmailRow) GetOrderItemID() pgtype.Int4 { return x.OrderItemID }

func (x GetOrderHistoryByUserEmailRow) GetOrderItemQuantity() pgtype.Int4 { return x.OrderItemQuantity }

func (x GetOrderHistoryByUserEmailRow) GetOrderItemPrice() pgtype.Numeric { return x.OrderItemPrice }

func (x GetOrderHistoryByUserEmailRow) GetProductID() pgtype.Int4 { return x.ProductID }

func (x GetOrderHistoryByUserEmailRow) GetProductName() pgtype.Text { return x.ProductName }

func (x GetOrderHistoryByUserEmailRow) GetProductDescription() pgtype.Text { return x.ProductDescription }

func (x GetOrderHistoryByUserEmailRow) GetProductPrice() pgtype.Numeric { return x.ProductPrice }

func (x GetOrderHistoryByUserEmailRow) GetProductStock() pgtype.Int4 { return x.ProductStock }

func (x GetOrderHistoryByUserEmailRow) GetProductBuyturn() pgtype.Int4 { return x.ProductBuyturn }

func (x GetOrderHistoryByUserEmailRow) GetProductImageUrl() pgtype.Text { return x.ProductImageUrl }

func (x GetOrderHistoryByUserEmailRow) GetBrandID() pgtype.Int4 { return x.BrandID }

func (x GetOrderHistoryByUserEmailRow) GetBrandName() pgtype.Text { return x.BrandName }

func (x GetOrderHistoryByUserEmailRow) GetBrandImageUrl() pgtype.Text { return x.BrandImageUrl }

func (x GetOrderHistoryByUserEmailRow) GetCategoryID() pgtype.Int4 { return x.CategoryID }

func (x GetOrderHistoryByUserEmailRow) GetCategoryName() pgtype.Text { return x.CategoryName }

func (x GetOrderHistoryByUserEmailRow) GetCategoryImageUrl() pgtype.Text { return x.CategoryImageUrl }

func (x GetOrderHistoryByUserEmailRow) GetTotal() *int64 { return x.Total }

