// Code generated by go:generate; DO NOT EDIT.
package repository

import "github.com/jackc/pgx/v5/pgtype"

func (x GetOrderHistoryByUserIDParams) GetUserID() pgtype.Int4 { return x.UserID }

func (x GetOrderHistoryByUserIDParams) GetLimit() int32 { return x.Limit }

func (x GetOrderHistoryByUserIDParams) GetOffset() int32 { return x.Offset }

func (x GetOrderHistoryByUserIDRow) GetID() int32 { return x.ID }

func (x GetOrderHistoryByUserIDRow) GetUserID() pgtype.Int4 { return x.UserID }

func (x GetOrderHistoryByUserIDRow) GetTotalPrice() pgtype.Numeric { return x.TotalPrice }

func (x GetOrderHistoryByUserIDRow) GetStatus() string { return x.Status }

func (x GetOrderHistoryByUserIDRow) GetShippingAddress() string { return x.ShippingAddress }

func (x GetOrderHistoryByUserIDRow) GetPhone() string { return x.Phone }

func (x GetOrderHistoryByUserIDRow) GetPaymentMethod() string { return x.PaymentMethod }

func (x GetOrderHistoryByUserIDRow) GetOrderDate() pgtype.Date { return x.OrderDate }

func (x GetOrderHistoryByUserIDRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetOrderHistoryByUserIDRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetOrderHistoryByUserIDRow) GetID_2() pgtype.Int4 { return x.ID_2 }

func (x GetOrderHistoryByUserIDRow) GetOrderID() pgtype.Int4 { return x.OrderID }

func (x GetOrderHistoryByUserIDRow) GetProductID() pgtype.Int4 { return x.ProductID }

func (x GetOrderHistoryByUserIDRow) GetQuantity() pgtype.Int4 { return x.Quantity }

func (x GetOrderHistoryByUserIDRow) GetPrice() pgtype.Numeric { return x.Price }

func (x GetOrderHistoryByUserIDRow) GetID_3() pgtype.Int4 { return x.ID_3 }

func (x GetOrderHistoryByUserIDRow) GetName() pgtype.Text { return x.Name }

func (x GetOrderHistoryByUserIDRow) GetDescription() pgtype.Text { return x.Description }

func (x GetOrderHistoryByUserIDRow) GetPrice_2() pgtype.Numeric { return x.Price_2 }

func (x GetOrderHistoryByUserIDRow) GetCategoryID() pgtype.Int4 { return x.CategoryID }

func (x GetOrderHistoryByUserIDRow) GetStock() pgtype.Int4 { return x.Stock }

func (x GetOrderHistoryByUserIDRow) GetBuyturn() pgtype.Int4 { return x.Buyturn }

func (x GetOrderHistoryByUserIDRow) GetImageUrl() pgtype.Text { return x.ImageUrl }

func (x GetOrderHistoryByUserIDRow) GetBrandID() pgtype.Int4 { return x.BrandID }

func (x GetOrderHistoryByUserIDRow) GetCreatedAt_2() pgtype.Timestamp { return x.CreatedAt_2 }

func (x GetOrderHistoryByUserIDRow) GetUpdatedAt_2() pgtype.Timestamp { return x.UpdatedAt_2 }

func (x GetOrderHistoryByUserIDRow) GetID_4() pgtype.Int4 { return x.ID_4 }

func (x GetOrderHistoryByUserIDRow) GetName_2() pgtype.Text { return x.Name_2 }

func (x GetOrderHistoryByUserIDRow) GetImageUrl_2() pgtype.Text { return x.ImageUrl_2 }

func (x GetOrderHistoryByUserIDRow) GetID_5() pgtype.Int4 { return x.ID_5 }

func (x GetOrderHistoryByUserIDRow) GetName_3() pgtype.Text { return x.Name_3 }

func (x GetOrderHistoryByUserIDRow) GetImageUrl_3() pgtype.Text { return x.ImageUrl_3 }

func (x GetOrderHistoryByUserIDRow) GetCreatedAt_3() pgtype.Timestamp { return x.CreatedAt_3 }

