// Code generated by go:generate; DO NOT EDIT.
package repository

import "github.com/jackc/pgx/v5/pgtype"

func (x GetOrderDetailByIDRow) GetID() int32 { return x.ID }

func (x GetOrderDetailByIDRow) GetOrderID() pgtype.Int4 { return x.OrderID }

func (x GetOrderDetailByIDRow) GetProductID() pgtype.Int4 { return x.ProductID }

func (x GetOrderDetailByIDRow) GetQuantity() int32 { return x.Quantity }

func (x GetOrderDetailByIDRow) GetPrice() pgtype.Numeric { return x.Price }

func (x GetOrderDetailByIDRow) GetProductID_2() pgtype.Int4 { return x.ProductID_2 }

func (x GetOrderDetailByIDRow) GetProductName() pgtype.Text { return x.ProductName }

func (x GetOrderDetailByIDRow) GetProductDescription() pgtype.Text { return x.ProductDescription }

func (x GetOrderDetailByIDRow) GetProductPrice() pgtype.Numeric { return x.ProductPrice }

func (x GetOrderDetailByIDRow) GetProductImageUrl() pgtype.Text { return x.ProductImageUrl }

func (x GetOrderDetailByIDRow) GetBrandID() pgtype.Int4 { return x.BrandID }

func (x GetOrderDetailByIDRow) GetBrandName() pgtype.Text { return x.BrandName }

func (x GetOrderDetailByIDRow) GetBrandImageUrl() pgtype.Text { return x.BrandImageUrl }

func (x GetOrderDetailByIDRow) GetCategoryName() pgtype.Text { return x.CategoryName }

func (x GetOrderDetailByIDRow) GetCategoryID() pgtype.Int4 { return x.CategoryID }

func (x GetOrderDetailByIDRow) GetCategoryImageUrl() pgtype.Text { return x.CategoryImageUrl }

func (x GetOrderHistoryByUserEmailParams) GetUserEmail() string { return x.UserEmail }

func (x GetOrderHistoryByUserEmailParams) GetLimit() int32 { return x.Limit }

func (x GetOrderHistoryByUserEmailParams) GetOffset() int32 { return x.Offset }

func (x GetOrderHistoryByUserEmailRow) GetID() int32 { return x.ID }

func (x GetOrderHistoryByUserEmailRow) GetUserEmail() string { return x.UserEmail }

func (x GetOrderHistoryByUserEmailRow) GetTotalPrice() pgtype.Numeric { return x.TotalPrice }

func (x GetOrderHistoryByUserEmailRow) GetStatus() string { return x.Status }

func (x GetOrderHistoryByUserEmailRow) GetShippingAddress() string { return x.ShippingAddress }

func (x GetOrderHistoryByUserEmailRow) GetPhone() string { return x.Phone }

func (x GetOrderHistoryByUserEmailRow) GetPaymentMethod() string { return x.PaymentMethod }

func (x GetOrderHistoryByUserEmailRow) GetOrderDate() pgtype.Date { return x.OrderDate }

func (x GetOrderHistoryByUserEmailRow) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x GetOrderHistoryByUserEmailRow) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x GetOrderHistoryByUserEmailRow) GetTotal() *int64 { return x.Total }

