// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID       int32       `json:"id"`
	Name     pgtype.Text `json:"name"`
	ImageUrl pgtype.Text `json:"image_url"`
}

type Cart struct {
	ID        int32            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CartItem struct {
	ID        int32          `json:"id"`
	CartID    pgtype.Int4    `json:"cart_id"`
	ProductID pgtype.Int4    `json:"product_id"`
	Quantity  pgtype.Int4    `json:"quantity"`
	Subtotal  pgtype.Numeric `json:"subtotal"`
}

type Category struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID              int32            `json:"id"`
	UserEmail       string           `json:"user_email"`
	TotalPrice      pgtype.Numeric   `json:"total_price"`
	ShippingFee     pgtype.Numeric   `json:"shipping_fee"`
	Status          string           `json:"status"`
	ShippingAddress string           `json:"shipping_address"`
	Phone           string           `json:"phone"`
	PaymentMethod   string           `json:"payment_method"`
	OrderDate       pgtype.Date      `json:"order_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	Notes           pgtype.Text      `json:"notes"`
}

type OrderItem struct {
	ID        int32          `json:"id"`
	OrderID   pgtype.Int4    `json:"order_id"`
	ProductID pgtype.Int4    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

type Product struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Price       pgtype.Numeric   `json:"price"`
	CategoryID  int32            `json:"category_id"`
	Stock       int32            `json:"stock"`
	Buyturn     int32            `json:"buyturn"`
	ImageUrl    string           `json:"image_url"`
	BrandID     int32            `json:"brand_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
