// Code generated by go:generate; DO NOT EDIT.
package repository

import "github.com/jackc/pgx/v5/pgtype"

func (x Brand) GetID() int32 { return x.ID }

func (x Brand) GetName() pgtype.Text { return x.Name }

func (x Brand) GetImageUrl() pgtype.Text { return x.ImageUrl }

func (x Cart) GetID() int32 { return x.ID }

func (x Cart) GetUserID() pgtype.Int4 { return x.UserID }

func (x Cart) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x Cart) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x CartItem) GetID() int32 { return x.ID }

func (x CartItem) GetCartID() pgtype.Int4 { return x.CartID }

func (x CartItem) GetProductID() pgtype.Int4 { return x.ProductID }

func (x CartItem) GetQuantity() pgtype.Int4 { return x.Quantity }

func (x CartItem) GetSubtotal() pgtype.Numeric { return x.Subtotal }

func (x Category) GetID() int32 { return x.ID }

func (x Category) GetName() string { return x.Name }

func (x Category) GetImageUrl() pgtype.Text { return x.ImageUrl }

func (x Category) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x Order) GetID() int32 { return x.ID }

func (x Order) GetUserEmail() string { return x.UserEmail }

func (x Order) GetTotalPrice() pgtype.Numeric { return x.TotalPrice }

func (x Order) GetStatus() string { return x.Status }

func (x Order) GetShippingAddress() string { return x.ShippingAddress }

func (x Order) GetPhone() string { return x.Phone }

func (x Order) GetPaymentMethod() string { return x.PaymentMethod }

func (x Order) GetOrderDate() pgtype.Date { return x.OrderDate }

func (x Order) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x Order) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x OrderItem) GetID() int32 { return x.ID }

func (x OrderItem) GetOrderID() pgtype.Int4 { return x.OrderID }

func (x OrderItem) GetProductID() pgtype.Int4 { return x.ProductID }

func (x OrderItem) GetQuantity() int32 { return x.Quantity }

func (x OrderItem) GetPrice() pgtype.Numeric { return x.Price }

func (x Product) GetID() int32 { return x.ID }

func (x Product) GetName() string { return x.Name }

func (x Product) GetDescription() pgtype.Text { return x.Description }

func (x Product) GetPrice() pgtype.Numeric { return x.Price }

func (x Product) GetCategoryID() int32 { return x.CategoryID }

func (x Product) GetStock() int32 { return x.Stock }

func (x Product) GetBuyturn() int32 { return x.Buyturn }

func (x Product) GetImageUrl() string { return x.ImageUrl }

func (x Product) GetBrandID() int32 { return x.BrandID }

func (x Product) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x Product) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

func (x User) GetID() int32 { return x.ID }

func (x User) GetName() string { return x.Name }

func (x User) GetEmail() string { return x.Email }

func (x User) GetPassword() string { return x.Password }

func (x User) GetRole() string { return x.Role }

func (x User) GetCreatedAt() pgtype.Timestamp { return x.CreatedAt }

func (x User) GetUpdatedAt() pgtype.Timestamp { return x.UpdatedAt }

