// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT count(DISTINCT o.id)
FROM
    orders o
    LEFT JOIN order_items oi ON o.id = oi.order_id
    LEFT JOIN products p ON oi.product_id = p.id
WHERE (
        $1::text IS NULL
        OR o.user_email = $1
    )
    AND (
        $2::int IS NULL
        OR oi.product_id = $2
    )
    AND (
        $3::int[] IS NULL
        OR p.brand_id = ANY (
            $3::int[]
        )
    )
    AND (
        $4::timestamp IS NULL
        OR o.order_date >= $4
    )
    AND (
        $5::timestamp IS NULL
        OR o.order_date <= $5
    )
    AND (
        $6::numeric IS NULL
        OR o.total_price >= $6::numeric
    )
    AND (
        $7::numeric IS NULL
        OR o.total_price <= $7::numeric
    )
`

type CountOrdersParams struct {
	UserEmail      string           `json:"user_email"`
	ProductID      int32            `json:"product_id"`
	BrandIds       []int32          `json:"brand_ids"`
	StartDate      pgtype.Timestamp `json:"start_date"`
	EndDate        pgtype.Timestamp `json:"end_date"`
	MinTotalAmount pgtype.Numeric   `json:"min_total_amount"`
	MaxTotalAmount pgtype.Numeric   `json:"max_total_amount"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (*int64, error) {
	row := q.db.QueryRow(ctx, countOrders,
		arg.UserEmail,
		arg.ProductID,
		arg.BrandIds,
		arg.StartDate,
		arg.EndDate,
		arg.MinTotalAmount,
		arg.MaxTotalAmount,
	)
	var count *int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
insert into
    orders(
        user_email,
        total_price,
        status,
        shipping_address,
        shipping_fee,
        phone,
        payment_method,
        order_date,
        notes
    )
values (
        $1,
        $2,
        'pending',
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
returning
    id, user_email, total_price, shipping_fee, status, shipping_address, phone, payment_method, order_date, created_at, updated_at, notes
`

type CreateOrderParams struct {
	UserEmail       string         `json:"user_email"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	ShippingAddress string         `json:"shipping_address"`
	ShippingFee     pgtype.Numeric `json:"shipping_fee"`
	Phone           string         `json:"phone"`
	PaymentMethod   string         `json:"payment_method"`
	OrderDate       pgtype.Date    `json:"order_date"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserEmail,
		arg.TotalPrice,
		arg.ShippingAddress,
		arg.ShippingFee,
		arg.Phone,
		arg.PaymentMethod,
		arg.OrderDate,
		arg.Notes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.TotalPrice,
		&i.ShippingFee,
		&i.Status,
		&i.ShippingAddress,
		&i.Phone,
		&i.PaymentMethod,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
insert into
    order_items (
        order_id,
        product_id,
        quantity,
        price
    )
values (
        $1::int,
        $2::int,
        $3::int,
        $4
    )
returning
    id, order_id, product_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID   int32          `json:"order_id"`
	ProductID int32          `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrderDetail = `-- name: GetOrderDetail :one
select o.id, o.user_email, o.total_price, o.shipping_fee, o.status, o.shipping_address, o.phone, o.payment_method, o.order_date, o.created_at, o.updated_at, o.notes, u.name as user_name
from orders o
left join users u on u.email = o.user_email
where
    o.id = $1
`

type GetOrderDetailRow struct {
	ID              int32            `json:"id"`
	UserEmail       string           `json:"user_email"`
	TotalPrice      pgtype.Numeric   `json:"total_price"`
	ShippingFee     pgtype.Numeric   `json:"shipping_fee"`
	Status          string           `json:"status"`
	ShippingAddress string           `json:"shipping_address"`
	Phone           string           `json:"phone"`
	PaymentMethod   string           `json:"payment_method"`
	OrderDate       pgtype.Date      `json:"order_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	Notes           pgtype.Text      `json:"notes"`
	UserName        pgtype.Text      `json:"user_name"`
}

func (q *Queries) GetOrderDetail(ctx context.Context, orderID int32) (GetOrderDetailRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetail, orderID)
	var i GetOrderDetailRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.TotalPrice,
		&i.ShippingFee,
		&i.Status,
		&i.ShippingAddress,
		&i.Phone,
		&i.PaymentMethod,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.UserName,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
select
    oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price,
    p.id as product_id,
    p.name as product_name,
    p.description as product_description,
    p.price as product_price,
    p.image_url as product_image_url
from order_items oi
    left join products p on p.id = oi.product_id
where
    oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID                 int32          `json:"id"`
	OrderID            pgtype.Int4    `json:"order_id"`
	ProductID          pgtype.Int4    `json:"product_id"`
	Quantity           int32          `json:"quantity"`
	Price              pgtype.Numeric `json:"price"`
	ProductID_2        pgtype.Int4    `json:"product_id_2"`
	ProductName        pgtype.Text    `json:"product_name"`
	ProductDescription pgtype.Text    `json:"product_description"`
	ProductPrice       pgtype.Numeric `json:"product_price"`
	ProductImageUrl    pgtype.Text    `json:"product_image_url"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.Int4) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsRow{}
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ProductID_2,
			&i.ProductName,
			&i.ProductDescription,
			&i.ProductPrice,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
    o.id, o.user_email, o.total_price, o.shipping_fee, o.status, o.shipping_address, o.phone, o.payment_method, o.order_date, o.created_at, o.updated_at, o.notes,
    count(*) OVER() AS total
FROM orders o
WHERE
    ($3::text IS NULL OR o.user_email = $3::text)
    AND ($4::int IS NULL OR o.id = $4::int)
    AND ($5::timestamp IS NULL OR o.order_date >= $5)
    AND ($6::timestamp IS NULL OR o.order_date <= $6)
    AND ($7::numeric IS NULL OR o.total_price >= $7::numeric)
    AND ($8::numeric IS NULL OR o.total_price <= $8::numeric)
    AND ($9::text IS NULL OR lower(o.status) = lower($9)::text)
ORDER BY
    CASE WHEN $10::text = 'order_date_asc' THEN o.order_date END ASC,
    CASE WHEN $10::text = 'order_date_desc' THEN o.order_date END DESC,
    CASE WHEN $10::text = 'total_amount_asc' THEN o.total_price END ASC,
    CASE WHEN $10::text = 'total_amount_desc' THEN o.total_price END DESC,
    o.id ASC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit          int32            `json:"limit"`
	Offset         int32            `json:"offset"`
	UserEmail      pgtype.Text      `json:"user_email"`
	OrderID        pgtype.Int4      `json:"order_id"`
	StartDate      pgtype.Timestamp `json:"start_date"`
	EndDate        pgtype.Timestamp `json:"end_date"`
	MinTotalAmount pgtype.Numeric   `json:"min_total_amount"`
	MaxTotalAmount pgtype.Numeric   `json:"max_total_amount"`
	Status         pgtype.Text      `json:"status"`
	OrderBy        string           `json:"order_by"`
}

type ListOrdersRow struct {
	ID              int32            `json:"id"`
	UserEmail       string           `json:"user_email"`
	TotalPrice      pgtype.Numeric   `json:"total_price"`
	ShippingFee     pgtype.Numeric   `json:"shipping_fee"`
	Status          string           `json:"status"`
	ShippingAddress string           `json:"shipping_address"`
	Phone           string           `json:"phone"`
	PaymentMethod   string           `json:"payment_method"`
	OrderDate       pgtype.Date      `json:"order_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	Notes           pgtype.Text      `json:"notes"`
	Total           *int64           `json:"total"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.Limit,
		arg.Offset,
		arg.UserEmail,
		arg.OrderID,
		arg.StartDate,
		arg.EndDate,
		arg.MinTotalAmount,
		arg.MaxTotalAmount,
		arg.Status,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.TotalPrice,
			&i.ShippingFee,
			&i.Status,
			&i.ShippingAddress,
			&i.Phone,
			&i.PaymentMethod,
			&i.OrderDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $1 WHERE id = $2 RETURNING id, user_email, total_price, shipping_fee, status, shipping_address, phone, payment_method, order_date, created_at, updated_at, notes
`

type UpdateOrderStatusParams struct {
	Status string `json:"status"`
	ID     int32  `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.TotalPrice,
		&i.ShippingFee,
		&i.Status,
		&i.ShippingAddress,
		&i.Phone,
		&i.PaymentMethod,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return i, err
}
