// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	IsUserExist(ctx context.Context, email string) error
	UpsertUSer(ctx context.Context, arg UpsertUSerParams) (User, error)
}

var _ Querier = (*Queries)(nil)
