// Code generated by go:generate; DO NOT EDIT.
package repository

func (x GetAllUsersParams) GetLimit() int32 { return x.Limit }

func (x GetAllUsersParams) GetOffset() int32 { return x.Offset }

func (x UpsertUSerParams) GetName() string { return x.Name }

func (x UpsertUSerParams) GetEmail() string { return x.Email }

func (x UpsertUSerParams) GetPassword() string { return x.Password }

func (x UpsertUSerParams) GetRole() string { return x.Role }

